version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --legacy-peer-deps
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install --legacy-peer-deps
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Deploying to S3 Bucket $BUCKET_NAME

      - aws s3 sync dist/ s3://$BUCKET_NAME/dap --delete --cache-control "max-age=0, no-cache, no-store, must-revalidate"

      - echo Build completed on `date`
