export enum Role {
  CSB_LIAISON = 'CSB_LIAISON',
  CSB_DAP_COORDINATOR = 'CSB_DAP_COORDINATOR',
  REGIONAL_MANAGER = 'REGIONAL_MANAGER',
  PROGRAM_ADMIN = 'PROGRAM_ADMIN',
  DBHDS_CTS = 'DBHDS_CTS',
  DBHDS_HOSPITAL_REP = 'DBHDS_HOSPITAL_REP',
  MEMBER_AT_LARGE = 'MEMBER_AT_LARGE',
}

export type UserRole = 'CSB_LIAISON' | 'CSB_DAP_COORDINATOR' |
  'REGIONAL_MANAGER' | 'PROGRAM_ADMIN' | 'DBHDS_CTS' |
  'DBHDS_HOSPITAL_REP' | 'MEMBER_AT_LARGE'
